# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 484cc342fa554651ea45bdf37acd26910f8cce4164bb4f7bc76e54f73831f7e5949d3b0ef50ee5edc2438e0b9ce05f75c8ec91ead8fc34b51c2700f214b951d1

test:
  secret_key_base: acf4eedf698c2100701389938060035ee4d7fccd06d9125eb6b436e2b17a2348b2357bb86c8f4fc0c7e0dfb068109147e0fc33077633d576536a9439d8cedb1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
